travis:
  secure:
    BINSTAR_TOKEN: EgNRuO93Dj+HYc5N0l2IaACZN7un1NXZmQSuZd573hm0MW2k/1xmTf49zyaCqqL6XpuVvhDBfeKukVbvL49Bx85SKbVMT6Wb0PqAfRtu8+oB1mWg9DXx8oNcfq2ylIMCpEZ+K8fCh8MRQmUfR9L5xvyN7iOtmtqE26WLb1SO2EimC3Ug2mUBkvxvYUmdupxGvxMtHAIN+y5kIzLd3lRxJjSmHxUSO5vl9m8EAflVD0qc8XfPW74FB9tZN0pQzKZA+jzoavwiGmrBYxHzlF28pqeQ8OzmIGD8n8jCeStMCLKDSgRF6h3rSJwZ7IdQQUBqE3Pa5JDEM4Lpnl5IzvHEUawQhmPKfOiOP5hYFHSF8YgMKgEqSAYHWKLNzQcERiMe3VQRnr+Td57Cmm5/N1ymk2gNJ6+vWC4vCuSew/C5FaSVeClhRHbMlvZIvfkjk8kI5WsRcN15/KJIsigz0Nl0BI/mxVovjWaxwl8e1rXTXB7MV91kD6ps07PJ872EpSklskl5ZRZBLX5lTqLU+aL3OAaq1JVW9WYcKQpWIZY9cmX3g/yNU+g2NOTRbDDc6cKR+YGzlbdUCBmD4OroKvNwMXlJYSN0/J6Ci5nDhkvdIZOl+ffb70gZsEQPxxwQVpTD+6gQ6VG1YyWCzT/4xrs2i5ztcqDXo9M/FS5TciIxN9g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
